### ISSUE TITLE
Pouvoir modifier un sondage

### ISSUE THREAD

**Issue by pasojucle** [pasojucle/vtt_evasion_ludres#228]

**Comment by pasojucle** [comment]
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/d1ecbcb4-e239-4c73-90a6-e063039fe4fb)

**Comment by VTTPierre** [comment]
Patrick
Cela ne semble pas fonctionner sur le site de test, j'ai tenté de créer un sondage auquel j'ai répondu mais je n'ai pas moyen de le modifier par la suite. 

J'ai également ajouté Sylvain dans la liste des autorisés et là en faisant enregistrer il bascule sur afficher le sondage à tous les adhérents. Bizarum!!!

https://github.com/pasojucle/vtt_evasion_ludres/assets/87672341/03c7dfc2-fecc-4713-a8d6-c72c392a953a

**Comment by pasojucle** [comment]
Bonjour @VTTPierre. Le but n''est pas de pouvoir modifier le contenu du sondage, mais que l'adhérent qui a répondu puisse changer d'avis. Dans le menu de l'adhérent, Mes sondage, sur la liste des sondages répondus et qui sont encore actifs, un bouton permet de modifier les réponses.
Par contre la modification du contenu d'un sondage a été bloqué volontairement, du moment ou au moins un des adhérent à répondu, car dans le cas contraire, tous ceux qui ont répondu ne sont pas au courant de la modification. Y a t-il un intérêt pour pouvoir modifier le contenu ?

**Comment by VTTPierre** [comment]
Ok je voisEn fait j'ai fait un sondage ce jour pour le choix du repas lors de notre rando et j'ai répondu pour ma part. je me suis aperçu qu'il manquait une précision donc j'ai voulu le corriger ou modifier mais pas possible donc j'ai refait un nouveau sondage en clôturant le premier car je ne peux pas le supprimer.Ensuite j'ai refait la manip sur le site de test et constaté qu'il en était de même pas de modif possible une fois répondu par un adhérent, mais comme tu l'expliques s'est logique.On laisse comme cela.J'ai toutefois noté un point bizarre lorsque j'ai créé le sondage il m'a proposé une date au 17/04 par défaut et non pas la date du jour. Est-ce logique ou non? car en le validant il se trouve inactif du coup.Bonne soiréeenvoyé : 9 avril 2024 à 18:29de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Pouvoir modifier un sondage (Issue #228) Bonjour @VTTPierre. Le but n''est pas de pouvoir modifier le contenu du sondage, mais que l'adhérent qui a répondu puisse changer d'avis. Dans le menu de l'adhérent, Mes sondage, sur la liste des sondages répondus et qui sont encore actifs, un bouton permet de modifier les réponses. Par contre la modification du contenu d'un sondage a été bloqué volontairement, du moment ou au moins un des adhérent à répondu, car dans le cas contraire, tous ceux qui ont répondu ne sont pas au courant de la modification. Y a t-il un intérêt pour pouvoir modifier le contenu ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pasojucle** [comment]
On peut modifier pour donner un peu plus de souplesse au système. Je propose que l'on permette de modifier le contenu et les question, pour corriger des coquilles, mais afficher le popup pour avertir ceux qui auraient déjà répondu. Qu'en penses-tu ?

**Comment by VTTPierre** [comment]
Ca me va. si c'est faisable pour toi.envoyé : 9 avril 2024 à 19:03de : pasojucle ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>cc : VTTPierre ***@***.***>, Mention ***@***.***>objet : Re: [pasojucle/vtt_evasion_ludres] Pouvoir modifier un sondage (Issue #228) On peut modifier pour donner un peu plus de souplesse au système. Je propose que l'on permette de modifier le contenu et les question, pour corriger des coquilles, mais afficher le popup pour avertir ceux qui auraient déjà répondu. Qu'en penses-tu ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
