### ISSUE TITLE
Faire un système de notifications

### ISSUE THREAD

**Issue by pasojucle** [pasojucle/vtt_evasion_ludres#236]
A chaque nouvelles photos insérées dans le diaporama, ou à chaque nouvelle actualité, il faudrait mettre une pastille de couleur avec un "N" au niveau du menu pour signifier les nouveaux éléments que l'utilisateur n'a pas consulté.

Plutôt que d'afficher des pop'up successifs à chaque changement de pages, pour alerter d'un nouveau sondage, d'un changement sur un sondage, d'une commande en cours, d'une inscription en cours ..., je propose d'afficher une seul fois le pop'up pour avertir qu'il y a des  notifications, et ajouter un bouton dans le menu avec le nombre de notifications à consulter dans une pastille de couleur.
![image](https://github.com/pasojucle/vtt_evasion_ludres/assets/54477272/dee6ca69-5063-4591-803f-938f9e36e0a1)
Au clique sur ce menu , on affiche la liste des notifications.
@sylvainvtt, @VTTPierre qu'en pensez-vous ?

**Comment by sylvainvtt** [comment]
Salut Patrick,On est bien d'accord, comme on en a parlé, qu'on affiche les notifications tant que la nouvelle info n'a pas été consultée ?Sinon, c'est OK pour moi👍 et merciSylvainEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 20/05/2024  11:05  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : [pasojucle/vtt_evasion_ludres] Faire un système de notifications (Issue #236) 
A chaque nouvelles photos insérées dans le diaporama, ou à chaque nouvelle actualité, il faudrait mettre une pastille de couleur avec un "N" au niveau du menu pour signifier les nouveaux éléments que l'utilisateur n'a pas consulté.
Plutôt que d'afficher des pop'up successifs à chaque changement de pages, pour alerter d'un nouveau sondage, d'un changement sur un sondage, d'une commande en cours, d'une inscription en cours ..., je propose d'afficher une seul fois le pop'up pour avertir qu'il y a des  notifications, et ajouter un bouton dans le menu avec le nombre de notifications à consulter dans une pastille de couleur.
image.png (view on web)
Au clique sur ce menu , on affiche la liste des notifications.
@sylvainvtt, @VTTPierre qu'en pensez-vous ?

**Comment by sylvainvtt** [comment]
BonsoirCa me semble pas mal comme système Par contre on laisse tout de même la possibilité de mettre un pop-up défini dans le temps si on souhaite rappeler que l'info demeure importante.A testerenvoyé : 20 mai 2024 à 21:33de : "sylvain.kohler" ***@***.***>à : pasojucle/vtt_evasion_ludres ***@***.***>, pasojucle/vtt_evasion_ludres ***@***.***>, Pierre ALBRECHT ***@***.***>cc : Mention ***@***.***>objet : RE: [pasojucle/vtt_evasion_ludres] Faire un système de notifications (Issue #236)Salut Patrick,On est bien d'accord, comme on en a parlé, qu'on affiche les notifications tant que la nouvelle info n'a pas été consultée ?Sinon, c'est OK pour moi👍 et merciSylvainEnvoyé depuis mon appareil Galaxy-------- Message d'origine --------De : pasojucle ***@***.***>Date : 20/05/2024 11:05 (GMT+01:00)À : pasojucle/vtt_evasion_ludres ***@***.***>Cc : sylvainvtt ***@***.***>, Mention ***@***.***>Objet : [pasojucle/vtt_evasion_ludres] Faire un système de notifications (Issue #236) A chaque nouvelles photos insérées dans le diaporama, ou à chaque nouvelle actualité, il faudrait mettre une pastille de couleur avec un "N" au niveau du menu pour signifier les nouveaux éléments que l'utilisateur n'a pas consulté.Plutôt que d'afficher des pop'up successifs à chaque changement de pages, pour alerter d'un nouveau sondage, d'un changement sur un sondage, d'une commande en cours, d'une inscription en cours ..., je propose d'afficher une seul fois le pop'up pour avertir qu'il y a des notifications, et ajouter un bouton dans le menu avec le nombre de notifications à consulter dans une pastille de couleur. image.png (view on web) Au clique sur ce menu , on affiche la liste des notifications. @sylvainvtt, @VTTPierre qu'en pensez-vous ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
