### ISSUE TITLE
Envoi de mail à l'issue des 3 séances d'essai

### ISSUE THREAD

**Issue by VTTPierre** [pasojucle/vtt_evasion_ludres#42]
Adresser un mail à chaque nouvel adhérent s'étant inscrit à la 3ème séance d'essai.

**Comment by pasojucle** [comment]
@sylvainvtt

voila le mail envoyé à l'inscription de la 3e séance. Dis moi ce que tu en penses

![Capture d’écran du 2021-09-11 13-04-03](https://user-images.githubusercontent.com/54477272/132945754-4d12c320-7ecf-40d0-af99-45ea6f4235df.png)

**Comment by pasojucle** [comment]
@sylvainvtt
A  l'inscription de la 3e séance, J'ajoute également un bouton dans "mon compte"

![Capture d’écran du 2021-09-11 14-20-23](https://user-images.githubusercontent.com/54477272/132947747-070ed297-bd4d-43b7-a620-672a563da103.png)

**Comment by pasojucle** [comment]
@sylvainvtt

A l'inscription de la 4e sortie

![Capture d’écran du 2021-09-12 17-05-53](https://user-images.githubusercontent.com/54477272/132992752-4866459b-5717-4719-bc46-fcceb5aaad98.png)

**Comment by sylvainvtt** [comment]
👍👍👍Salut Patrick,C'est bien, c'est bloquant mais avec une invitation 😁.  Bien vu.Mervi et bonne soiréeSylvainEnvoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : pasojucle ***@***.***> Date : 12/09/2021  17:19  (GMT+01:00) À : pasojucle/vtt_evasion_ludres ***@***.***> Cc : sylvainvtt ***@***.***>, Mention ***@***.***> Objet : Re: [pasojucle/vtt_evasion_ludres] Envoi de mail à l'issue des 3 séances d'essai (#42) 

@sylvainvtt

A l'inscription de la 4e sortie





—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/pasojucle/vtt_evasion_ludres/issues/42#issuecomment-917656060",

"url": "https://github.com/pasojucle/vtt_evasion_ludres/issues/42#issuecomment-917656060",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
